MQTTBroker = "localhost:1883"
MQTTUser = "conix"
MQTTPass = "stream"
WAVEAgent = "localhost:410"
WAVEEntity = "register.ent"
Namespace = "GyALwtmePnvwhXGmoQPjuW8ZIANlsqG_-P7nvISdwQ-9RQ=="
Pset = "GyAa2eh0Ksh4eYdmHiAVuU7Hf2tyy06QbkrLke1ho0WS_Q=="
RegistrationTopic = "register"
