#!/usr/bin/env python3

import conixposter
import argparse
parser = argparse.ArgumentParser()

#each call must have a uuid first
parser.add_argument("uuid",help="The unique identifier for a sensor",type=str)

#we can then have multiple values with a sensor type, value and unit
parser.add_argument('-w','--write', action='append', metavar=('type','value','unit'),nargs=3, help='At least one value must be posted as a type, value, unit tuple')

#now parse the arguments we got and do the post
args = parser.parse_args()

print(args)
